### ISSUE TITLE
ERROR [px4] Startup script returned with return value: 256

### ISSUE THREAD

**Issue by yousef337** [CopterExpress/clover#496]
I have been following the documentation at
https://github.com/CopterExpress/clover/blob/master/docs/en/simulation_native.md for running the simulation in ROS Noetic and have faced the following error 

Error: no autostart file found (**********/init.d-posix/airframes/4500_clover)
ERROR [px4] Startup script returned with return value: 256

during running roslaunch clover_simulation simulator.launch

**Comment by okalachev** [comment]
What virtual machine to you use, and were there any errors during the installation?

Also, can you please provide the full output log of this command, maybe it can help to investigate the reason of this error.

**Comment by yousef337** [comment]
I am not using a virtual machine, I am running EndeavourOS that contains an apptainer container running Ubuntu, which I use to run the whole process. The only error that occures was #495, the current error occurs when I rem aruco_pose in order to make the catkin_make run successfully.

**Comment by okalachev** [comment]
Are you sure you have symlinked simulated Clover airframe to PX4 sources as required in [this step](https://github.com/CopterExpress/clover/blob/master/docs/en/simulation_native.md#add-the-clover-airframe)?

**Comment by yousef337** [comment]
Yes, and checked manually, the file is there

**Comment by yousef337** [comment]
After resolving #495, the error stack is the same,

Error: no autostart file found (****/init.d-posix/airframes/4500_clover)
ERROR [px4] Startup script returned with return value: 256
================================================================================REQUIRED process [sitl_0-3] has died!
process has died [pid 558325, exit code 255, cmd ***/devel/lib/px4/px4 ***/src/PX4-Autopilot/ROMFS/px4fmu_common -s etc/init.d-posix/rcS -i 0 __name:=sitl_0 __log:=****/.ros/log/f7aa0c6e-691b-11ee-87cf-84fdd1142c15/sitl_0-3.log].
log file: *****/.ros/log/f7aa0c6e-691b-11ee-87cf-84fdd1142c15/sitl_0-3*.log
Initiating shutdown!
================================================================================
RLException: cannot add process [vpe_publisher-8] after process monitor has been shut down
The traceback for the exception was written to the log file

**Comment by yousef337** [comment]
Sometimes, if running the launch file again, gazeboo does open with the empty world, along with the error messages. However, running topics-related command doesn't seem to function properly. 

For example, running rostopic echo /mavros/local_position/pose would result in WARNING: no messages received and simulated time is active.
Is /clock being published?

**Comment by okalachev** [comment]
I don't get why px4 binary can't find the `4500_clover` airframe file, if you say, that you have symlinked it as in the manual.

Please, check, if there is a following file: `~/.ros/etc/init.d-posix/airframes/4500_clover`.

**Comment by yousef337** [comment]
It is, were you able to replicate the issue? Can you go through the setup docs?

**Comment by MagicWinnie** [comment]
Fixed same issue by manually creating a symlink:  
`ln -sf ~/catkin_ws/src/clover/clover_simulation/airframes/*  ~/.ros/etc/init.d-posix/airframes/`  
I guess I have made a mistake while creating a symlink per instructions in docs.

**Comment by yousef337** [comment]
Unfortunately it didn't resolve the issue

**Comment by yousef337** [comment]
When ls ~/.ros/etc/init.d-posix/airframes/, I would still get 4500_clover. When ls -la, it would yield .ros/etc/init.d-posix/airframes/4500_clover -> src/clover/clover_simulation/airframes/4500_clover

**Comment by okalachev** [comment]
Closed as stale.
